version: "3"
services:
  backend:
    container_name: backend
    logging:
      options:
        max-size: "50m"
    image: zipkortnicks57/foxkids_online:backend
    environment: 
      ENV_FOR_DYNACONF: production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./series_settings/:/series_settings/
      - /foxkids_full/:/mnt/:ro
      - ./html/:/src/html/:ro
    networks:
      - foxkids_network

networks:
  foxkids_network:
    driver: bridge