services:
  backend:
    container_name: backend
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    volumes:
      - C://Users//User//Videos//foxkids_full/:/mnt/:ro
      - ./html:/src/html:ro
    environment: 
      ENV_FOR_DYNACONF: development
    networks:
      - foxkids_network
    ports:
      - 8001:8000

networks:
  foxkids_network:
    driver: bridge
    name: foxkids_network