services:
  backend:
    container_name: backend
    build: 
      context: ./
      dockerfile: Dockerfile-dev
    env_file: 
      - ./.env
    volumes:
      - C://Users//User//Videos//foxkids_full/:/mnt/
    networks:
      - foxkids_network

networks:
  foxkids_network:
    driver: bridge
    name: foxkids_network