services:
  backend:
    container_name: backend
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      ENV_FOR_DYNACONF: production
    volumes:
      - ./series_settings/:/series_settings/
      - /foxkids_full/:/mnt/
      - ./html/:/src/html/
    networks:
      - foxkids_network

networks:
  foxkids_network:
    driver: bridge
    name: foxkids_network