
production:
  COUNT_COMMERTIALS: 2
  TIME_START: 07:00
  STREAM_URL: rtmp://server:1935/stream/test #адрес внутреннего контейнера nginx
  MAIN_FOLDER: /mnt/foxkids #адрес папки с сериалами прод контейнера
  FILE_PROGRAM: /series_settings/program.json
  FILE_SERIES: /series_settings/series.json
  FILE_STREAM: /series_settings/stream.sh
  PROMO_FOLDER: reklama # адрес папки реклам внутри расшаренной папки
  BLOCK_PROMO_FOLDER: reklama_block
  COMMERTIALS_FOLDER: reklama_random
  PLAY_SCRIPT: ffmpeg  -re -i {} -c:a aac -c:v libx264 -b:v 200k -b:a 64K -r 25 -s 320x240 -f flv {}
  CURL_SCRIPT: "curl -X POST http://server/api/current_promo -H \"Content-Type: application/json\" -d '{{\"current_series\": \"{}\", \"next_series\": \"{}\"}}'"
  PORT: 8000