test:
  COUNT_COMMERTIALS: 1
  TIME_START: 07:00
  STREAM_URL: rtmp://server_rtmp:1935/stream/test
  MAIN_FOLDER: tests/test_mnt_sample/foxkids
  FILE_PROGRAM: tests/test_mnt_sample/program.json
  FILE_SERIES: tests/test_mnt_sample/series.json
  FILE_STREAM: tests/test_mnt_sample/stream.sh
  PROMO_FOLDER: reklama
  BLOCK_PROMO_FOLDER: reklama_block
  COMMERTIALS_FOLDER: reklama_random
  PLAY_SCRIPT: ffmpeg  -re -i {} -c:a aac -c:v libx264 -b:v 200k -b:a 64K -r 25 -s 320x240 -f flv {}
  CURL_SCRIPT: "curl -X POST http://127.0.0.1/api/current_series/ -H \"Content-Type: application/json\" -d '{{\"current_series\": \"{}\", \"next_series\": \"{}\"}}'"
  PORT: 8002
