# Доставка фронтенда на сервер

name: cd-series

on:
  pull_request:
    branches: [ "main" ]

  # позволяет ручной запуск
  workflow_dispatch:
jobs:
  frontend:
    name: Add html files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add series configs
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: series_settings/*
          target: ${{ vars.WORKDIR }}/backend/
     
