# Доставка на сервер

name: cd

on:
  pull_request:
    branches: [ "main" ]

  # позволяет ручной запуск
  workflow_dispatch:
  
jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
    #   - name: Install python3.12
    #     run: apt install python3.12
      - name: Install poetry
        run: pip3 install poetry && poetry init && poetry shell
      - name: Install linters
        run: poetry install --with dev
      - name: Isort cheking
        run: isort  --diff  --settings-path pyproject.toml .
      - name: Black cheking
        run: isort  --diff  --config pyproject.toml .
      - name: Flake8 cheking
        run: flake8 --config pyproject.toml .
      - name: Mypy cheking
        run: mypy --config pyproject.toml .